#!/usr/bin/env python3
"""One-shot migration : aligne les tags des recettes sur _taxonomy.yaml (ADR 0029).

Lit chaque `recipes/*.md`, normalise les tags via la table d'aliases du
_taxonomy.yaml, supprime les tags qui doublent le champ `role` ou
`duration_minutes` (cf. ADR §1), et applique quelques enrichissements
éditoriaux ponctuels listés explicitement ci-dessous.

Dry-run par défaut. Nécessite `--apply` pour réécrire les fichiers.

Le script est idempotent : un second passage après une migration réussie
ne produit aucun changement.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
TAXONOMY_FILE = REPO_ROOT / "_taxonomy.yaml"
RECIPES_DIR = REPO_ROOT / "recipes"

# Tags retirés sans remplacement : doublent un champ structuré ou sont
# du bruit (cf. ADR 0029 §1).
DROP_TAGS: set[str] = {
    # Doublons de Recipe.role
    "gateau",
    "dessert",
    "tarte",
    "patisserie",
    "gratin",
    "plat-principal",
    "plat principal",
    "pate",  # toujours sur des role=preparation (pâte brisée/sablée/sucrée)
    # Doublons de Recipe.duration_minutes
    "facile",
    "bon-marche",
    # Bruit / contexte non structurant
    "automne",
    "maison",
    "sale",
    "recette",
    # Redondant avec cuisine indien/thai/oriental (ADR §1)
    "epice",
}

# Enrichissements éditoriaux explicites : recettes qui méritent un tag
# absent du frontmatter d'origine. À garder court et justifié — chaque
# entrée est une décision humaine, pas une déduction automatique.
ENRICHMENTS: dict[str, list[str]] = {
    "tarte-tatin-de-poireaux.md": ["vegetarien"],
}


def load_alias_table() -> dict[str, str]:
    """Build a flat {alias_or_canonical: canonical} lookup from _taxonomy.yaml."""
    raw = yaml.safe_load(TAXONOMY_FILE.read_text(encoding="utf-8"))
    table: dict[str, str] = {}
    for axis, entries in raw.items():
        for entry in entries:
            canonical = entry["canonical"]
            table[canonical] = canonical
            for alias in entry.get("aliases") or []:
                table[alias] = canonical
    return table


def split_frontmatter(text: str) -> tuple[dict[str, Any], str, str]:
    """Return (frontmatter_dict, frontmatter_yaml_str, body)."""
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.DOTALL)
    if not m:
        raise ValueError("missing or malformed YAML frontmatter")
    fm_yaml = m.group(1)
    body = m.group(2)
    fm = yaml.safe_load(fm_yaml) or {}
    return fm, fm_yaml, body


def rewrite_tags_in_yaml(fm_yaml: str, new_tags: list[str]) -> str:
    """Replace the `tags:` line/block in the original YAML, preserving order
    and formatting of the other fields.

    Handles three input shapes seen in the corpus :
      tags: []
      tags: [a, b]
      tags:
        - a            (2-space indent — typical)
      tags:
      - a              (0-space indent — generated by some tools)

    The replacement always emits 2-space-indented block style for non-empty
    lists, and `[]` for the empty case (mirrors what `recipe_serializer.py`
    in projectx writes).
    """
    lines = fm_yaml.split("\n")
    out: list[str] = []
    i = 0
    replaced = False
    while i < len(lines):
        line = lines[i]
        if not replaced and re.match(r"^tags:[ \t]*", line):
            # Either `tags: [..]` (single-line) or `tags:` followed by list items.
            head = line.split(":", 1)[1].strip()
            if head.startswith("["):
                # Flow style — single line, drop it entirely.
                pass
            else:
                # Block style — drop subsequent lines that are list items
                # (start with optional spaces then `- `). Stop at first
                # non-list line (the next key).
                j = i + 1
                while j < len(lines) and re.match(r"^[ \t]*-[ \t]+", lines[j]):
                    j += 1
                i = j - 1  # so the outer i+=1 lands on the next non-list line
            # Emit the new tags block.
            if new_tags:
                out.append("tags:")
                for t in new_tags:
                    out.append(f"  - {t}")
            else:
                out.append("tags: []")
            replaced = True
        else:
            out.append(line)
        i += 1

    if not replaced:
        # No `tags:` key in the original — append it at the end.
        if new_tags:
            out.append("tags:")
            for t in new_tags:
                out.append(f"  - {t}")
        else:
            out.append("tags: []")

    return "\n".join(out)


def migrate_recipe(
    path: Path, alias_table: dict[str, str]
) -> tuple[list[str], list[str], list[str]]:
    """Compute (old_tags, new_tags, unmapped) for a single recipe.

    Does not write — the caller decides based on --apply.
    Returns:
      - old_tags : original list as in the file
      - new_tags : canonicalised + deduped list (preserves first-seen order)
      - unmapped : tags neither in the alias table nor in DROP_TAGS
    """
    text = path.read_text(encoding="utf-8")
    fm, _fm_yaml, _body = split_frontmatter(text)
    old_tags = list(fm.get("tags") or [])
    new_tags: list[str] = []
    unmapped: list[str] = []

    for raw in old_tags:
        t = str(raw).strip()
        if t in DROP_TAGS:
            continue
        if t in alias_table:
            canonical = alias_table[t]
            if canonical not in new_tags:
                new_tags.append(canonical)
            continue
        unmapped.append(t)

    # Apply explicit enrichments (idempotent: only add if missing).
    for extra in ENRICHMENTS.get(path.name, []):
        if extra in alias_table and extra not in new_tags:
            new_tags.append(extra)

    return old_tags, new_tags, unmapped


def write_recipe(path: Path, new_tags: list[str]) -> None:
    """Rewrite path with the updated tags block, preserving everything else."""
    text = path.read_text(encoding="utf-8")
    fm, fm_yaml, body = split_frontmatter(text)
    new_fm_yaml = rewrite_tags_in_yaml(fm_yaml, new_tags)
    new_text = f"---\n{new_fm_yaml.rstrip()}\n---\n{body}"
    path.write_text(new_text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apply", action="store_true", help="actually rewrite the files"
    )
    parser.add_argument(
        "--path",
        type=Path,
        default=RECIPES_DIR,
        help="recipes directory (default: ./recipes)",
    )
    args = parser.parse_args()

    alias_table = load_alias_table()

    files = sorted(p for p in args.path.glob("*.md"))
    if not files:
        print(f"no .md files under {args.path}", file=sys.stderr)
        return 1

    n_changed = 0
    n_unchanged = 0
    n_unmapped_total = 0
    unmapped_global: dict[str, list[str]] = {}

    for f in files:
        try:
            old, new, unmapped = migrate_recipe(f, alias_table)
        except ValueError as exc:
            print(f"⚠️  {f.name}: {exc}", file=sys.stderr)
            continue

        if unmapped:
            unmapped_global[f.name] = unmapped
            n_unmapped_total += len(unmapped)

        if old == new:
            n_unchanged += 1
            continue

        n_changed += 1
        marker = "✏️ " if args.apply else "🔍"
        print(f"{marker} {f.name}")
        print(f"    before: {old}")
        print(f"    after : {new}")
        if args.apply:
            write_recipe(f, new)

    print()
    print("══ SUMMARY ══")
    print(f"  Recettes modifiées : {n_changed} / {len(files)}")
    print(f"  Recettes inchangées: {n_unchanged}")
    if unmapped_global:
        print(f"  ⚠️  Tags non mappés ({n_unmapped_total} occurrences) :")
        for fname, tags in unmapped_global.items():
            print(f"      {fname}: {tags}")
        print("    → ajoute-les à _taxonomy.yaml ou à DROP_TAGS, puis rejoue")
        return 2 if args.apply else 0
    if not args.apply:
        print()
        print("  → relance avec --apply pour écrire les fichiers")
    return 0


if __name__ == "__main__":
    sys.exit(main())
